// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peliculas.Persitence.Database;

namespace Peliculas.Persitence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Peliculas")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Peliculas.Domain.Pelicula", b =>
                {
                    b.Property<int>("PeliculaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoGeneroID")
                        .HasColumnType("int");

                    b.HasKey("PeliculaID");

                    b.HasIndex("TipoGeneroID");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaID = 1,
                            Clave = "P001",
                            Nombre = "El silencio de los inocentes",
                            TipoGeneroID = 1
                        });
                });

            modelBuilder.Entity("Peliculas.Domain.TipoGenero", b =>
                {
                    b.Property<int>("TipoGeneroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoGeneroID");

                    b.ToTable("TipoGeneros");

                    b.HasData(
                        new
                        {
                            TipoGeneroID = 1,
                            Descripcion = "Drama"
                        });
                });

            modelBuilder.Entity("Peliculas.Domain.Pelicula", b =>
                {
                    b.HasOne("Peliculas.Domain.TipoGenero", "Genero")
                        .WithMany()
                        .HasForeignKey("TipoGeneroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });
#pragma warning restore 612, 618
        }
    }
}
